[tool.pyrefly]
# Жестко ограничиваем зону поиска только текущей папкой
search_path = ["."]
# Запрещаем лезть в глобальные библиотеки и виртуальные окружения
exclude = [
    "**/node_modules",
    "**/.venv",
    "**/venv",
    "**/site-packages",
    "**/__pycache__"
]
